### PR TITLE
Update media codecs to latest stock

### PR DESCRIPTION
**Pull request by dariotrombello**
Took this one from BunsExynos as he already removed the unnecessary parts in the config

### CODE REVIEW

**Comment by Stricted** [comment]
the `audio_effects.conf` change is not relevant, we dont use that file, we use https://github.com/Exynos7580/android_device_samsung_exynos7580-common/blob/lineage-15.1/configs/audio/audio_effects.xml which has the libdownmix.so entry (and it gets loaded correctly from vendor)

about the media_codes changes: im not sure if we should do this, the current ones works fine and since we had our issues with it in the past i dont like touching it unless its really needed

**Comment by dariotrombello** [comment]
Is it okay now? xD

**Comment by Stricted** [comment]
remove the audio_effects.conf changes entirely they are useless

also let me test the media codec changes for a few days, i want to be sure that it doesnt cause any problems

**Comment by Stricted** [comment]
also tell me please from which stock version these changes come from

**Comment by dariotrombello** [comment]
A5 2016 U4. And no they don't make any problems. I use them already in my test builds and everything works.

**Comment by dariotrombello** [comment]
But if you don't like it i'll keep it for me. I can tell you anyway that the audio paths are correct now (at least on my A3) and the media codec update also works flawlessy.

**Comment by Stricted** [comment]
the paths in `audio_effects.conf` are entirely irrelevant for 2 reasons
1. we dont use that file (its only for reference there)
2. i added the `../` on purpose (yet it doesnt matter because we dont use that file and in `audio_effects.xmlf` these audio filter are deactivated)

the same actually counts for `media_codecs_performance.xml` this file is not in use (also here just for completeness, but these changes are ok)
and the actual `media_codecs.xml` well i want test them myself before i merge it in (i hate to randomly merge stuff in without having tested them)

**Comment by Stricted** [comment]
ok i tested the changes now and surely it works with no issues so far
nevertheless im not going to merge this, i pulled the files from A310FXXU4CRG2 (which matches our blobs) and i get a different change then you, i will push it and give you the credit for it

**Comment by Stricted** [comment]
https://github.com/Exynos7580/android_device_samsung_exynos7580-common/commit/d2914091dcd2998aa5f647aeb53bdf50c7431c6c

**Pull request closed without merging**
