### PR TITLE
ril: Adjust the RIL_SMS_Response structure to match vendor definition

### PR DESCRIPTION
**Pull request by ghost**
Used commit from : https://github.com/exynos5420/android_device_samsung_klimtlte/commit/4a2d0c7e5549e35fdbe341791fb8b0eee6b34a3f

### CODE REVIEW

**Comment by messi2050** [comment]
You are very active guys xD, how stable latest builds on your devices ?

**Comment by Stricted** [comment]
on the s5 neo the rom seems to work pretty well
the biggest bug currently is the audio stuff

**Comment by messi2050** [comment]
Incall audio is not working ?

**Comment by Stricted** [comment]
on calling audio is working, but on for example recording the audio is just awfull

**Comment by ghost** [comment]
@messi2050 bugs remaining are :
- Microphone (except in calls)
- Tether/Hotspot (can be RIL related)
- Battery draining
- Some other I think 

(On the A3 2016, LineageOS and Resurrection Remix)

_Sent from my Samsung SM-A310F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by aapav01** [comment]
hotspot is a kernel bug

**Comment by ghost** [comment]
@aapav01 do u now something that can help to fix that?

**Pull request merged**
