### PR TITLE
overlay: Show up missing LTE option in preferred network type

### PR DESCRIPTION
**Pull request by vishalk17**

### CODE REVIEW

**Comment by dariotrombello** [comment]
Its already defined in the a3xelte device tree. Maybe it should be removed there before this can be merged

**Comment by vishalk17** [comment]
It is missing for j7 2015

**Comment by vishalk17** [comment]
I thought exynos7580 support lte .. if yes then it should be in common overlay

**Comment by dariotrombello** [comment]
But are you sure this is the right way to enable LTE in the prefered network type selection? Because on the A3 device tree we use this
`<string name="config_radio_access_family">GSM | WCDMA | LTE</string>`

**Comment by vishalk17** [comment]
I dont have such a above thing in one of mine device tree.( You can check here https://github.com/vishalk17/android_device_leeco_x3/search?q=lte&unscoped_q=lte ). But i have only " config_enabled_lte "

At the end  I m sure about it..

**Comment by vishalk17** [comment]
To make sure You  can test this commit before merge...

**Comment by danwood76** [comment]
> I thought exynos7580 support lte .. if yes then it should be in common overlay

Not all Exynos7580 devices have GSM so this should be in the device specific tree.

On the A3 we have the same option in the device overlays as well as the key from Borduni (so you have both LTE plus correct selection of 3G/LTE).

**Comment by vishalk17** [comment]
Ok..fine..  Add LTE in preferred network for j7 2015..because it is missing there ..

**Pull request closed without merging**
